[target.'cfg(target_family = "wasm")']
rustflags = [
  "-C", "target-feature=+atomics",
  "-C", "target-feature=+bulk-memory",
  "-C", "target-feature=+mutable-globals",
  "-C", "link-arg=--shared-memory",
  "-C", "link-arg=--max-memory=1073741824",
  "-C", "link-arg=--import-memory",
  "-C", "link-arg=--export=__wasm_init_tls",
  "-C", "link-arg=--export=__tls_base",
  "-C", "link-arg=--export=__tls_size",
  "-C", "link-arg=--export=__tls_align",
]
